<?php

use App\Http\Controllers\AccessRightController;
use App\Http\Controllers\ActivityLogController;
use App\Http\Controllers\AddressController;
use App\Http\Controllers\AdjustmentController;
use App\Http\Controllers\AppMenuController;
use App\Http\Controllers\CityController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\CourierController;
use App\Http\Controllers\CurrencyController;
use App\Http\Controllers\DeliveryFeeController;
use App\Http\Controllers\GlobalSettingController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\MaterialController;
use App\Http\Controllers\MeasurementCategoryController;
use App\Http\Controllers\MeasurementController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\OperationTypeController;
use App\Http\Controllers\PaymentTermController;
use App\Http\Controllers\ProductCategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RegionController;
use App\Http\Controllers\SalesOrderController;
use App\Http\Controllers\SalesOrderLineController;
use App\Http\Controllers\SequenceController;
use App\Http\Controllers\SourceController;
use App\Http\Controllers\StockMovementController;
use App\Http\Controllers\TransferController;
use App\Http\Controllers\UploadController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\GroupController;
use App\Http\Controllers\WarehouseController;
use App\Models\AccessRight;
use App\Models\Address;
use App\Models\Adjustment;
use App\Models\AppMenu;
use App\Models\City;
use App\Models\Contact;
use App\Models\Country;
use App\Models\Courier;
use App\Models\Currency;
use App\Models\DeliveryFee;
use App\Models\GlobalSetting;
use App\Models\Location;
use App\Models\Material;
use App\Models\Measurement;
use App\Models\MeasurementCategory;
use App\Models\Menu;
use App\Models\OperationType;
use App\Models\PaymentTerm;
use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\Region;
use App\Models\SalesOrder;
use App\Models\SalesOrderLine;
use App\Models\Sequence;
use App\Models\Source;
use App\Models\StockMovement;
use App\Models\Transfer;
use App\Models\User;
use App\Models\Group;
use App\Models\Warehouse;
use App\Services\Router;
use Illuminate\Support\Facades\Route;
use Spatie\Activitylog\Models\Activity;

Route::group(['middleware' => ['api', 'cors']], function () {
    Route::post('/tokens/create', [LoginController::class, 'tokensCreate']);
    Route::post('/sanctum/token', [LoginController::class, 'authenticate']);
});

Route::group(['middleware' => ['api', 'cors', 'auth:sanctum']], function () {
    (new Router(AccessRight::class))::generate(AccessRightController::class);
    (new Router(Activity::class))::generate(ActivityLogController::class);
    (new Router(Address::class))::generate(AddressController::class);
    (new Router(Adjustment::class))::generate(AdjustmentController::class);
    (new Router(AppMenu::class))::generate(AppMenuController::class);
    (new Router(City::class))::generate(CityController::class);
    (new Router(Contact::class))::generate(ContactController::class);
    (new Router(Country::class))::generate(CountryController::class);
    (new Router(Courier::class))::generate(CourierController::class);
    (new Router(Currency::class))::generate(CurrencyController::class);
    (new Router(DeliveryFee::class))::generate(DeliveryFeeController::class);
    (new Router(GlobalSetting::class))::generate(GlobalSettingController::class);
    (new Router(Location::class))::generate(LocationController::class);
    Route::post('/logout', [LoginController::class, 'logout']);
    (new Router(Material::class))::generate(MaterialController::class);
    (new Router(MeasurementCategory::class))::generate(MeasurementCategoryController::class);
    (new Router(Measurement::class))::generate(MeasurementController::class);
    (new Router(Menu::class))::generate(MenuController::class);
    (new Router(OperationType::class))::generate(OperationTypeController::class);
    (new Router(PaymentTerm::class))::generate(PaymentTermController::class);
    (new Router(ProductCategory::class))::generate(ProductCategoryController::class);
    (new Router(Region::class))::generate(RegionController::class);
    Route::get("sales_orders/sales_per_day", [SalesOrderController::class, 'sales_per_day']);
    (new Router(SalesOrder::class))::generate(SalesOrderController::class);
    (new Router(SalesOrderLine::class))::generate(SalesOrderLineController::class);
    (new Router(Product::class))::generate(ProductController::class);
    (new Router(Sequence::class))::generate(SequenceController::class);
    (new Router(Source::class))::generate(SourceController::class);
    (new Router(StockMovement::class))::generate(StockMovementController::class);
    (new Router(Transfer::class))::generate(TransferController::class);
    Route::post('uploads/images', [UploadController::class, 'image']);
    (new Router(User::class))::generate(UserController::class);
    (new Router(Group::class))::generate(GroupController::class);
    (new Router(Warehouse::class))::generate(WarehouseController::class);
});
