<?php

namespace App\Jobs;

use App\Models\GlobalSetting;
use App\Models\Product;
use App\Models\SalesOrder;
use App\Models\SalesOrderLine;
use App\Models\Sequence;
use App\Models\Transfer;
use Carbon\Carbon;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class ImportManualOrdersJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function handle()
    {
        $orders = [
            [
                'date' => 'MAY 2020',
                'items' => [
                    ['sku' => 'KL', 'quantity' => 428],
                    ['sku' => 'KM', 'quantity' => 679],
                    ['sku' => 'SS', 'quantity' => 31],
                    ['sku' => 'SM', 'quantity' => 52],
                    ['sku' => 'SL', 'quantity' => 24],
                ]
            ],
            [
                'date' => 'JUNE 2020',
                'items' => [
                    ['sku' => 'KL', 'quantity' => 818],
                    ['sku' => 'KM', 'quantity' => 1163],
                    ['sku' => 'SS', 'quantity' => 340],
                    ['sku' => 'SM', 'quantity' => 537],
                    ['sku' => 'SL', 'quantity' => 294],
                    ['sku' => 'US', 'quantity' => 176],
                    ['sku' => 'UM', 'quantity' => 184],
                    ['sku' => 'UL', 'quantity' => 137],
                ]
            ],
            [
                'date' => 'JULY 2020',
                'items' => [
                    ['sku' => 'KL', 'quantity' => 776],
                    ['sku' => 'KM', 'quantity' => 903],
                    ['sku' => 'SS', 'quantity' => 326],
                    ['sku' => 'SM', 'quantity' => 433],
                    ['sku' => 'SL', 'quantity' => 259],
                    ['sku' => 'US', 'quantity' => 210],
                    ['sku' => 'UM', 'quantity' => 195],
                    ['sku' => 'UL', 'quantity' => 152],
                ]
            ],
            [
                'date' => 'AUG 2020',
                'items' => [
                    ['sku' => 'KL', 'quantity' => 337],
                    ['sku' => 'KM', 'quantity' => 398],
                    ['sku' => 'KS', 'quantity' => 9],
                    ['sku' => 'SL', 'quantity' => 115],
                    ['sku' => 'SM', 'quantity' => 132],
                    ['sku' => 'SS', 'quantity' => 99],
                    ['sku' => 'TL', 'quantity' => 49],
                    ['sku' => 'TM', 'quantity' => 43],
                    ['sku' => 'TS', 'quantity' => 47],
                    ['sku' => 'UL', 'quantity' => 59],
                    ['sku' => 'UM', 'quantity' => 82],
                    ['sku' => 'US', 'quantity' => 77]
                ]
            ],
            [
                'date' => 'SEP 2020',
                'items' => [
                    ['sku' => 'KL', 'quantity' => 319],
                    ['sku' => 'KM', 'quantity' => 322],
                    ['sku' => 'KS', 'quantity' => 3],
                    ['sku' => 'SL', 'quantity' => 104],
                    ['sku' => 'SM', 'quantity' => 183],
                    ['sku' => 'SMS', 'quantity' => 1],
                    ['sku' => 'SS', 'quantity' => 141],
                    ['sku' => 'SSS', 'quantity' => 1],
                    ['sku' => 'TL', 'quantity' => 39],
                    ['sku' => 'TM', 'quantity' => 50],
                    ['sku' => 'TS', 'quantity' => 31],
                    ['sku' => 'UL', 'quantity' => 49],
                    ['sku' => 'UM', 'quantity' => 75],
                    ['sku' => 'US', 'quantity' => 49],
                    ['sku' => 'USS', 'quantity' => 1],
                ]
            ],
            [
                'date' => 'OCT 2020',
                'items' => [
                    ['sku' => 'AMS', 'quantity' => 1],
                    ['sku' => 'KL', 'quantity' => 292],
                    ['sku' => 'KLS', 'quantity' => 2],
                    ['sku' => 'KM', 'quantity' => 298],
                    ['sku' => 'KMS', 'quantity' => 2],
                    ['sku' => 'KS', 'quantity' => 2],
                    ['sku' => 'SL', 'quantity' => 108],
                    ['sku' => 'SM', 'quantity' => 185],
                    ['sku' => 'SS', 'quantity' => 144],
                    ['sku' => 'TL', 'quantity' => 15],
                    ['sku' => 'TM', 'quantity' => 22],
                    ['sku' => 'TS', 'quantity' => 12],
                    ['sku' => 'UL', 'quantity' => 43],
                    ['sku' => 'UM', 'quantity' => 44],
                    ['sku' => 'US', 'quantity' => 50],
                ]
            ],
            [
                'date' => 'NOV 2020',
                'items' => [
                    ['sku' => 'ALM', 'quantity' => 4],
                    ['sku' => 'ALS', 'quantity' => 21],
                    ['sku' => 'AMM', 'quantity' => 10],
                    ['sku' => 'AMS', 'quantity' => 27],
                    ['sku' => 'ASM', 'quantity' => 8],
                    ['sku' => 'ASS', 'quantity' => 24],
                    ['sku' => 'KL', 'quantity' => 259],
                    ['sku' => 'KLS', 'quantity' => 1],
                    ['sku' => 'KM', 'quantity' => 196],
                    ['sku' => 'KMS', 'quantity' => 2],
                    ['sku' => 'KS', 'quantity' => 1],
                    ['sku' => 'SL', 'quantity' => 122],
                    ['sku' => 'SM', 'quantity' => 129],
                    ['sku' => 'SMS', 'quantity' => 1],
                    ['sku' => 'SS', 'quantity' => 99],
                    ['sku' => 'SSS', 'quantity' => 2],
                    ['sku' => 'TL', 'quantity' => 22],
                    ['sku' => 'TM', 'quantity' => 27],
                    ['sku' => 'TS', 'quantity' => 23],
                    ['sku' => 'UL', 'quantity' => 33],
                    ['sku' => 'UM', 'quantity' => 31],
                    ['sku' => 'US', 'quantity' => 28],
                ]
            ],
            [
                'date' => 'DEC 2020',
                'items' => [
                    ['sku' => 'ALM', 'quantity' => 2],
                    ['sku' => 'ALS', 'quantity' => 62],
                    ['sku' => 'AMM', 'quantity' => 4],
                    ['sku' => 'AMS', 'quantity' => 24],
                    ['sku' => 'ASM', 'quantity' => 3],
                    ['sku' => 'ASS', 'quantity' => 20],
                    ['sku' => 'KL', 'quantity' => 567],
                    ['sku' => 'KLS', 'quantity' => 3],
                    ['sku' => 'KM', 'quantity' => 441],
                    ['sku' => 'KMS', 'quantity' => 4],
                    ['sku' => 'SH', 'quantity' => 5],
                    ['sku' => 'SM', 'quantity' => 294],
                    ['sku' => 'SMS', 'quantity' => 4],
                    ['sku' => 'SL', 'quantity' => 191],
                    ['sku' => 'SLS', 'quantity' => 4],
                    ['sku' => 'SS', 'quantity' => 118],
                    ['sku' => 'TL', 'quantity' => 63],
                    ['sku' => 'TLS', 'quantity' => 2],
                    ['sku' => 'TM', 'quantity' => 44],
                    ['sku' => 'TS', 'quantity' => 21],
                    ['sku' => 'UL', 'quantity' => 71],
                    ['sku' => 'UM', 'quantity' => 45],
                    ['sku' => 'UMS', 'quantity' => 2],
                    ['sku' => 'US', 'quantity' => 36],
                ]
            ],
            [
                'date' => 'JAN 2021',
                'items' => [
                    ['sku' => 'ALM', 'quantity' => 1],
                    ['sku' => 'ALS', 'quantity' => 12],
                    ['sku' => 'AMM', 'quantity' => 1],
                    ['sku' => 'AMS', 'quantity' => 20],
                    ['sku' => 'ASM', 'quantity' => 5],
                    ['sku' => 'ASS', 'quantity' => 9],
                    ['sku' => 'KL', 'quantity' => 220],
                    ['sku' => 'KLS', 'quantity' => 2],
                    ['sku' => 'KM', 'quantity' => 217],
                    ['sku' => 'KMS', 'quantity' => 5],
                    ['sku' => 'SH', 'quantity' => 45],
                    ['sku' => 'SL', 'quantity' => 107],
                    ['sku' => 'SM', 'quantity' => 143],
                    ['sku' => 'SMS', 'quantity' => 4],
                    ['sku' => 'SS', 'quantity' => 83],
                    ['sku' => 'SSS', 'quantity' => 1],
                    ['sku' => 'TL', 'quantity' => 29],
                    ['sku' => 'TM', 'quantity' => 19],
                    ['sku' => 'TS', 'quantity' => 10],
                    ['sku' => 'UL', 'quantity' => 28],
                    ['sku' => 'UM', 'quantity' => 30],
                    ['sku' => 'US', 'quantity' => 28],
                ]
            ],
            [
                'date' => 'FEB 2021',
                'items' => [
                    ['sku' => 'ALS', 'quantity' => 7],
                    ['sku' => 'AMM', 'quantity' => 1],
                    ['sku' => 'AMS', 'quantity' => 19],
                    ['sku' => 'ASM', 'quantity' => 22],
                    ['sku' => 'ASS', 'quantity' => 3],
                    ['sku' => 'KL', 'quantity' => 250],
                    ['sku' => 'KLS', 'quantity' => 4],
                    ['sku' => 'KM', 'quantity' => 255],
                    ['sku' => 'KMS', 'quantity' => 4],
                    ['sku' => 'SH', 'quantity' => 28],
                    ['sku' => 'SL', 'quantity' => 110],
                    ['sku' => 'SLS', 'quantity' => 1],
                    ['sku' => 'SM', 'quantity' => 136],
                    ['sku' => 'SMS', 'quantity' => 4],
                    ['sku' => 'SS', 'quantity' => 80],
                    ['sku' => 'TL', 'quantity' => 35],
                    ['sku' => 'TM', 'quantity' => 22],
                    ['sku' => 'TS', 'quantity' => 7],
                    ['sku' => 'UL', 'quantity' => 33],
                    ['sku' => 'UM', 'quantity' => 38],
                    ['sku' => 'US', 'quantity' => 31],
                ]
            ],


            [
                'date' => 'MAR 2021',
                'items' => [
                    ['sku' => 'ALS', 'quantity' => 5],
                    ['sku' => 'AMS', 'quantity' => 34],
                    ['sku' => 'ASS', 'quantity' => 4],
                    ['sku' => 'KL', 'quantity' => 236],
                    ['sku' => 'KLS', 'quantity' => 2],
                    ['sku' => 'KM', 'quantity' => 250],
                    ['sku' => 'KMS', 'quantity' => 2],
                    ['sku' => 'SH', 'quantity' => 32],
                    ['sku' => 'SL', 'quantity' => 90],
                    ['sku' => 'SM', 'quantity' => 163],
                    ['sku' => 'SMS', 'quantity' => 4],
                    ['sku' => 'SS', 'quantity' => 87],
                    ['sku' => 'US', 'quantity' => 29],
                    ['sku' => 'UM', 'quantity' => 28],
                    ['sku' => 'UL', 'quantity' => 23],
                    ['sku' => 'TS', 'quantity' => 11],
                    ['sku' => 'TM', 'quantity' => 30],
                    ['sku' => 'TL', 'quantity' => 16],
                ]
            ],


            [
                'date' => 'APR 2021',
                'items' => [
                    ['sku' => 'KM', 'quantity' => 322],
                    ['sku' => 'KMS', 'quantity' => 4],
                    ['sku' => 'KL', 'quantity' => 267],
                    ['sku' => 'KLS', 'quantity' => 6],
                    ['sku' => 'KS', 'quantity' => 3],
                    ['sku' => 'KSS', 'quantity' => 1],
                    ['sku' => 'SS', 'quantity' => 123],
                    ['sku' => 'SSS', 'quantity' => 1],
                    ['sku' => 'SM', 'quantity' => 225],
                    ['sku' => 'SMS', 'quantity' => 6],
                    ['sku' => 'SL', 'quantity' => 121],
                    ['sku' => 'SLS', 'quantity' => 1],
                    ['sku' => 'US', 'quantity' => 38],
                    ['sku' => 'UM', 'quantity' => 30],
                    ['sku' => 'UMS', 'quantity' => 1],
                    ['sku' => 'UL', 'quantity' => 35],
                    ['sku' => 'TS', 'quantity' => 14],
                    ['sku' => 'TM', 'quantity' => 41],
                    ['sku' => 'TL', 'quantity' => 22],
                    ['sku' => 'ASS', 'quantity' => 11],
                    ['sku' => 'AMM', 'quantity' => 2],
                    ['sku' => 'AMS', 'quantity' => 46],
                    ['sku' => 'ALM', 'quantity' => 1],
                    ['sku' => 'ALS', 'quantity' => 10],
                    ['sku' => 'SH', 'quantity' => 34],
                    ['sku' => 'WSM', 'quantity' => 70],
                    ['sku' => 'WMM', 'quantity' => 139],
                    ['sku' => 'WLM', 'quantity' => 87],
                    ['sku' => 'WSS', 'quantity' => 27],
                    ['sku' => 'WMS', 'quantity' => 19],
                    ['sku' => 'WLS', 'quantity' => 11],
                ]
            ],
            [
                'date' => 'MAY 2021',
                'items' => [
                    ['sku' => 'KM', 'quantity' => 253],
                    ['sku' => 'KMS', 'quantity' => 4],
                    ['sku' => 'KL', 'quantity' => 252],
                    ['sku' => 'KLS', 'quantity' => 7],
                    ['sku' => 'SS', 'quantity' => 98],
                    ['sku' => 'SM', 'quantity' => 208],
                    ['sku' => 'SMS', 'quantity' => 6],
                    ['sku' => 'SL', 'quantity' => 112],
                    ['sku' => 'US', 'quantity' => 15],
                    ['sku' => 'UM', 'quantity' => 35],
                    ['sku' => 'UMS', 'quantity' => 1],
                    ['sku' => 'UL', 'quantity' => 38],
                    ['sku' => 'TS', 'quantity' => 14],
                    ['sku' => 'TM', 'quantity' => 36],
                    ['sku' => 'TL', 'quantity' => 57],
                    ['sku' => 'ASM', 'quantity' => 1],
                    ['sku' => 'ASS', 'quantity' => 6],
                    ['sku' => 'AMS', 'quantity' => 16],
                    ['sku' => 'ALM', 'quantity' => 6],
                    ['sku' => 'ALS', 'quantity' => 10],
                    ['sku' => 'SH', 'quantity' => 36],
                    ['sku' => 'WSM', 'quantity' => 11],
                    ['sku' => 'WMM', 'quantity' => 24],
                    ['sku' => 'WLM', 'quantity' => 39],
                    ['sku' => 'WSS', 'quantity' => 5],
                    ['sku' => 'WMS', 'quantity' => 9],
                    ['sku' => 'WLS', 'quantity' => 3],
                ]
            ],


            [
                'date' => 'JUN 2021',
                'items' => [
                    ['sku' => 'KM', 'quantity' => 207],
                    ['sku' => 'KMS', 'quantity' => 3],
                    ['sku' => 'KL', 'quantity' => 237],
                    ['sku' => 'KLS', 'quantity' => 2],
                    ['sku' => 'SS', 'quantity' => 67],
                    ['sku' => 'SSS', 'quantity' => 2],
                    ['sku' => 'SM', 'quantity' => 158],
                    ['sku' => 'SMS', 'quantity' => 3],
                    ['sku' => 'SL', 'quantity' => 134],
                    ['sku' => 'US', 'quantity' => 22],
                    ['sku' => 'UM', 'quantity' => 50],
                    ['sku' => 'UMS', 'quantity' => 1],
                    ['sku' => 'UL', 'quantity' => 26],
                    ['sku' => 'TS', 'quantity' => 20],
                    ['sku' => 'TM', 'quantity' => 44],
                    ['sku' => 'TL', 'quantity' => 40],
                    ['sku' => 'ASM', 'quantity' => 1],
                    ['sku' => 'ASS', 'quantity' => 8],
                    ['sku' => 'AMM', 'quantity' => 1],
                    ['sku' => 'AMS', 'quantity' => 15],
                    ['sku' => 'ALM', 'quantity' => 1],
                    ['sku' => 'ALS', 'quantity' => 10],
                    ['sku' => 'SH', 'quantity' => 13],
                    ['sku' => 'WSM', 'quantity' => 8],
                    ['sku' => 'WMM', 'quantity' => 12],
                    ['sku' => 'WLM', 'quantity' => 10],
                    ['sku' => 'WSS', 'quantity' => 4],
                    ['sku' => 'WMS', 'quantity' => 5],
                    ['sku' => 'WLS', 'quantity' => 2],
                ]
            ],
            [
                'date' => 'JULY 2021',
                'items' => [
                    ['sku' => 'KS', 'quantity' => 1],
                    ['sku' => 'KM', 'quantity' => 257],
                    ['sku' => 'KMS', 'quantity' => 7],
                    ['sku' => 'KL', 'quantity' => 263],
                    ['sku' => 'KLS', 'quantity' => 5],
                    ['sku' => 'SS', 'quantity' => 64],
                    ['sku' => 'SSS', 'quantity' => 2],
                    ['sku' => 'SM', 'quantity' => 188],
                    ['sku' => 'SMS', 'quantity' => 6],
                    ['sku' => 'SL', 'quantity' => 140],
                    ['sku' => 'SLS', 'quantity' => 4],
                    ['sku' => 'US', 'quantity' => 32],
                    ['sku' => 'USS', 'quantity' => 43],
                    ['sku' => 'UM', 'quantity' => 43],
                    ['sku' => 'UL', 'quantity' => 44],
                    ['sku' => 'TS', 'quantity' => 10],
                    ['sku' => 'TM', 'quantity' => 41],
                    ['sku' => 'TMS', 'quantity' => 1],
                    ['sku' => 'TL', 'quantity' => 40],
                    ['sku' => 'ASM', 'quantity' => 3],
                    ['sku' => 'ASS', 'quantity' => 9],
                    ['sku' => 'AMM', 'quantity' => 4],
                    ['sku' => 'AMS', 'quantity' => 16],
                    ['sku' => 'ALS', 'quantity' => 18],
                    ['sku' => 'WSM', 'quantity' => 6],
                    ['sku' => 'WMM', 'quantity' => 29],
                    ['sku' => 'WLM', 'quantity' => 8],
                    ['sku' => 'WSS', 'quantity' => 2],
                    ['sku' => 'WMS', 'quantity' => 2],
                    ['sku' => 'WLS', 'quantity' => 1],
                    ['sku' => 'SH', 'quantity' => 11],
                ]
            ],


            [
                'date' => 'AUG 2021',
                'items' => [
                    ['sku' => 'KS', 'quantity' => 2],
                    ['sku' => 'KM', 'quantity' => 331],
                    ['sku' => 'KL', 'quantity' => 364],
                    ['sku' => 'KLS', 'quantity' => 2],
                    ['sku' => 'SS', 'quantity' => 110],
                    ['sku' => 'SM', 'quantity' => 204],
                    ['sku' => 'SMS', 'quantity' => 2],
                    ['sku' => 'SL', 'quantity' => 113],
                    ['sku' => 'US', 'quantity' => 19],
                    ['sku' => 'UM', 'quantity' => 30],
                    ['sku' => 'UL', 'quantity' => 30],
                    ['sku' => 'TS', 'quantity' => 33],
                    ['sku' => 'TM', 'quantity' => 64],
                    ['sku' => 'TL', 'quantity' => 65],
                    ['sku' => 'ASM', 'quantity' => 12],
                    ['sku' => 'ASS', 'quantity' => 14],
                    ['sku' => 'AMM', 'quantity' => 5],
                    ['sku' => 'AMS', 'quantity' => 23],
                    ['sku' => 'ALM', 'quantity' => 3],
                    ['sku' => 'ALS', 'quantity' => 11],
                    ['sku' => 'WSM', 'quantity' => 11],
                    ['sku' => 'WMM', 'quantity' => 36],
                    ['sku' => 'WLM', 'quantity' => 11],
                    ['sku' => 'WSS', 'quantity' => 9],
                    ['sku' => 'WMS', 'quantity' => 6],
                    ['sku' => 'WLS', 'quantity' => 1],
                    ['sku' => 'SH', 'quantity' => 27],
                ]
            ],
            [
                'date' => 'SEP 2021',
                'items' => [
                    ['sku' => 'KS', 'quantity' => 15],
                    ['sku' => 'KM', 'quantity' => 260],
                    ['sku' => 'KMS', 'quantity' => 2],
                    ['sku' => 'KL', 'quantity' => 370],
                    ['sku' => 'KLS', 'quantity' => 1],
                    ['sku' => 'SS', 'quantity' => 107],
                    ['sku' => 'SM', 'quantity' => 165],
                    ['sku' => 'SL', 'quantity' => 120],
                    ['sku' => 'US', 'quantity' => 31],
                    ['sku' => 'UM', 'quantity' => 28],
                    ['sku' => 'UMS', 'quantity' => 1],
                    ['sku' => 'UL', 'quantity' => 24],
                    ['sku' => 'TS', 'quantity' => 28],
                    ['sku' => 'TM', 'quantity' => 55],
                    ['sku' => 'TL', 'quantity' => 75],
                    ['sku' => 'ASM', 'quantity' => 3],
                    ['sku' => 'ASS', 'quantity' => 29],
                    ['sku' => 'AMM', 'quantity' => 7],
                    ['sku' => 'AMS', 'quantity' => 13],
                    ['sku' => 'ALM', 'quantity' => 5],
                    ['sku' => 'ALS', 'quantity' => 10],
                    ['sku' => 'WSM', 'quantity' => 1],
                    ['sku' => 'WMM', 'quantity' => 15],
                    ['sku' => 'WLM', 'quantity' => 35],
                    ['sku' => 'WSS', 'quantity' => 11],
                    ['sku' => 'WMS', 'quantity' => 2],
                    ['sku' => 'WLS', 'quantity' => 1],
                    ['sku' => 'GS', 'quantity' => 38],
                    ['sku' => 'GM', 'quantity' => 61],
                    ['sku' => 'GL', 'quantity' => 72],
                    ['sku' => 'SH', 'quantity' => 29],
                ]
            ],
            [
                'date' => 'OCT 2021',
                'items' => [
                    ['sku' => 'KS', 'quantity' => 19],
                    ['sku' => 'KM', 'quantity' => 263],
                    ['sku' => 'KMS', 'quantity' => 8],
                    ['sku' => 'KL', 'quantity' => 364],
                    ['sku' => 'KLS', 'quantity' => 9],
                    ['sku' => 'SS', 'quantity' => 124],
                    ['sku' => 'SSS', 'quantity' => 2],
                    ['sku' => 'SM', 'quantity' => 192],
                    ['sku' => 'SMS', 'quantity' => 3],
                    ['sku' => 'SL', 'quantity' => 118],
                    ['sku' => 'SLS', 'quantity' => 1],
                    ['sku' => 'US', 'quantity' => 16],
                    ['sku' => 'USS', 'quantity' => 2],
                    ['sku' => 'UM', 'quantity' => 26],
                    ['sku' => 'UL', 'quantity' => 33],
                    ['sku' => 'TS', 'quantity' => 30],
                    ['sku' => 'TM', 'quantity' => 52],
                    ['sku' => 'TMS', 'quantity' => 2],
                    ['sku' => 'TL', 'quantity' => 53],
                    ['sku' => 'ASM', 'quantity' => 4],
                    ['sku' => 'ASS', 'quantity' => 23],
                    ['sku' => 'AMM', 'quantity' => 6],
                    ['sku' => 'AMS', 'quantity' => 29],
                    ['sku' => 'ALM', 'quantity' => 4],
                    ['sku' => 'ALS', 'quantity' => 19],
                    ['sku' => 'WSM', 'quantity' => 5],
                    ['sku' => 'WMM', 'quantity' => 9],
                    ['sku' => 'WLM', 'quantity' => 11],
                    ['sku' => 'WSS', 'quantity' => 5],
                    ['sku' => 'WMS', 'quantity' => 8],
                    ['sku' => 'GS', 'quantity' => 30],
                    ['sku' => 'GM', 'quantity' => 64],
                    ['sku' => 'GL', 'quantity' => 52],
                    ['sku' => 'SH', 'quantity' => 31],
                    ['sku' => 'ES', 'quantity' => 11],
                    ['sku' => 'EM', 'quantity' => 8],
                    ['sku' => 'EL', 'quantity' => 9],
                    ['sku' => 'ZT', 'quantity' => 8],
                    ['sku' => 'ZH', 'quantity' => 14],
                    ['sku' => 'ZSS', 'quantity' => 3],
                    ['sku' => 'ZDA', 'quantity' => 2],
                    ['sku' => 'ZDB', 'quantity' => 3],
                    ['sku' => 'ZDC', 'quantity' => 1],
                ]
            ],
            [
                'date' => 'NOV 2021',
                'items' => [
                    ['sku' => 'KSS', 'quantity' => 7],
                    ['sku' => 'KS', 'quantity' => 23],
                    ['sku' => 'KM', 'quantity' => 202],
                    ['sku' => 'KMS', 'quantity' => 16],
                    ['sku' => 'KL', 'quantity' => 288],
                    ['sku' => 'KLS', 'quantity' => 15],
                    ['sku' => 'SS', 'quantity' => 84],
                    ['sku' => 'SSS', 'quantity' => 12],
                    ['sku' => 'SM', 'quantity' => 163],
                    ['sku' => 'SMS', 'quantity' => 2],
                    ['sku' => 'SL', 'quantity' => 82],
                    ['sku' => 'SLS', 'quantity' => 2],
                    ['sku' => 'US', 'quantity' => 14],
                    ['sku' => 'UM', 'quantity' => 34],
                    ['sku' => 'UL', 'quantity' => 19],
                    ['sku' => 'ULS', 'quantity' => 1],
                    ['sku' => 'TS', 'quantity' => 26],
                    ['sku' => 'TSS', 'quantity' => 1],
                    ['sku' => 'TM', 'quantity' => 45],
                    ['sku' => 'TMS', 'quantity' => 1],
                    ['sku' => 'TL', 'quantity' => 30],
                    ['sku' => 'ASM', 'quantity' => 10],
                    ['sku' => 'ASS', 'quantity' => 10],
                    ['sku' => 'AMM', 'quantity' => 6],
                    ['sku' => 'AMS', 'quantity' => 22],
                    ['sku' => 'ALM', 'quantity' => 7],
                    ['sku' => 'ALS', 'quantity' => 15],
                    ['sku' => 'WSM', 'quantity' => 10],
                    ['sku' => 'WMM', 'quantity' => 10],
                    ['sku' => 'WLM', 'quantity' => 10],
                    ['sku' => 'WSS', 'quantity' => 3],
                    ['sku' => 'WMS', 'quantity' => 1],
                    ['sku' => 'GS', 'quantity' => 27],
                    ['sku' => 'GM', 'quantity' => 52],
                    ['sku' => 'GL', 'quantity' => 30],
                    ['sku' => 'SH', 'quantity' => 16],
                    ['sku' => 'ES', 'quantity' => 5],
                    ['sku' => 'EM', 'quantity' => 3],
                    ['sku' => 'EL', 'quantity' => 6],
                    ['sku' => 'ZT', 'quantity' => 25],
                    ['sku' => 'ZH', 'quantity' => 75],
                    ['sku' => 'ZSS', 'quantity' => 20],
                    ['sku' => 'ZSM', 'quantity' => 16],
                    ['sku' => 'ZSL', 'quantity' => 13],
                    ['sku' => 'ZXTS', 'quantity' => 1],
                    ['sku' => 'ZHK', 'quantity' => 6],
                    ['sku' => 'ZDA', 'quantity' => 16],
                    ['sku' => 'ZDB', 'quantity' => 17],
                    ['sku' => 'ZDC', 'quantity' => 7],
                    ['sku' => 'ZDD', 'quantity' => 1],
                    ['sku' => 'ZCA', 'quantity' => 37],
                    ['sku' => 'ZCB', 'quantity' => 128],
                    ['sku' => 'ZCC', 'quantity' => 48],
                    ['sku' => 'ZCD', 'quantity' => 18],
                    ['sku' => 'ZMF', 'quantity' => 9],
                    ['sku' => 'ZMD', 'quantity' => 11],
                    ['sku' => 'ZME', 'quantity' => 13],
                    ['sku' => 'ZMM', 'quantity' => 12],
                    ['sku' => 'ZMA', 'quantity' => 18],
                    ['sku' => 'ZMS', 'quantity' => 12],
                    ['sku' => 'ZMT', 'quantity' => 7],
                    ['sku' => 'ZMI', 'quantity' => 4],
                    ['sku' => 'ZTM', 'quantity' => 5],
                    ['sku' => 'ZTE', 'quantity' => 3],
                    ['sku' => 'ZTU', 'quantity' => 4],
                    ['sku' => 'ZXS', 'quantity' => 3],
                    ['sku' => 'ZXB', 'quantity' => 1],
                    ['sku' => 'ZXM', 'quantity' => 1],
                    ['sku' => 'ZXA', 'quantity' => 4],
                    ['sku' => 'ZXT', 'quantity' => 3],
                    ['sku' => 'ZXW', 'quantity' => 2],
                    ['sku' => 'ZHE', 'quantity' => 3],
                    ['sku' => 'ZHI', 'quantity' => 1],
                    ['sku' => 'ZHS', 'quantity' => 1],
                    ['sku' => 'ZNBA', 'quantity' => 4],
                    ['sku' => 'ZNT', 'quantity' => 1],
                    ['sku' => 'ZNB', 'quantity' => 3],
                    ['sku' => 'ZNU', 'quantity' => 3],
                    ['sku' => 'ZNA', 'quantity' => 1],
                    ['sku' => 'ZNK', 'quantity' => 1],
                    ['sku' => 'ZNI', 'quantity' => 3],
                    ['sku' => 'ZNF', 'quantity' => 4],
                    ['sku' => 'ZNTC', 'quantity' => 1],
                    ['sku' => 'ZNTO', 'quantity' => 1],
                    ['sku' => 'ZNHB', 'quantity' => 2],
                    ['sku' => 'ZGU', 'quantity' => 3],
                    ['sku' => 'ZGW', 'quantity' => 2],
                    ['sku' => 'ZGE', 'quantity' => 3],
                ]
            ],
            [
                'date' => 'DEC 2021',
                'items' => [
                    ['sku' => 'KSS', 'quantity' => 1],
                    ['sku' => 'KS', 'quantity' => 36],
                    ['sku' => 'KM', 'quantity' => 519],
                    ['sku' => 'KMS', 'quantity' => 14],
                    ['sku' => 'KL', 'quantity' => 750],
                    ['sku' => 'KLS', 'quantity' => 24],
                    ['sku' => 'SS', 'quantity' => 105],
                    ['sku' => 'SSS', 'quantity' => 7],
                    ['sku' => 'SM', 'quantity' => 289],
                    ['sku' => 'SMS', 'quantity' => 11],
                    ['sku' => 'SL', 'quantity' => 274],
                    ['sku' => 'SLS', 'quantity' => 4],
                    ['sku' => 'US', 'quantity' => 14],
                    ['sku' => 'UM', 'quantity' => 57],
                    ['sku' => 'UMS', 'quantity' => 2],
                    ['sku' => 'UL', 'quantity' => 47],
                    ['sku' => 'TS', 'quantity' => 35],
                    ['sku' => 'TSS', 'quantity' => 1],
                    ['sku' => 'TM', 'quantity' => 77],
                    ['sku' => 'TMS', 'quantity' => 2],
                    ['sku' => 'TL', 'quantity' => 111],
                    ['sku' => 'ASM', 'quantity' => 34],
                    ['sku' => 'ASS', 'quantity' => 19],
                    ['sku' => 'AMM', 'quantity' => 54],
                    ['sku' => 'AMS', 'quantity' => 20],
                    ['sku' => 'ALM', 'quantity' => 30],
                    ['sku' => 'ALS', 'quantity' => 40],
                    ['sku' => 'WSM', 'quantity' => 4],
                    ['sku' => 'WMM', 'quantity' => 5],
                    ['sku' => 'WLM', 'quantity' => 7],
                    ['sku' => 'WSS', 'quantity' => 1],
                    ['sku' => 'WMS', 'quantity' => 8],
                    ['sku' => 'WLS', 'quantity' => 1],
                    ['sku' => 'GS', 'quantity' => 15],
                    ['sku' => 'GM', 'quantity' => 27],
                    ['sku' => 'GL', 'quantity' => 50],
                    ['sku' => 'SH', 'quantity' => 56],
                    ['sku' => 'ES', 'quantity' => 10],
                    ['sku' => 'EM', 'quantity' => 5],
                    ['sku' => 'EL', 'quantity' => 9],
                    ['sku' => 'ZT', 'quantity' => 36],
                    ['sku' => 'ZH', 'quantity' => 64],
                    ['sku' => 'ZSS', 'quantity' => 12],
                    ['sku' => 'ZSM', 'quantity' => 20],
                    ['sku' => 'ZSL', 'quantity' => 31],
                    ['sku' => 'ZXTS', 'quantity' => 5],
                    ['sku' => 'ZMTS', 'quantity' => 8],
                    ['sku' => 'ZHK', 'quantity' => 1],
                    ['sku' => 'ZDA', 'quantity' => 6],
                    ['sku' => 'ZDB', 'quantity' => 9],
                    ['sku' => 'ZDC', 'quantity' => 3],
                    ['sku' => 'ZDD', 'quantity' => 2],
                    ['sku' => 'ZCA', 'quantity' => 121],
                    ['sku' => 'ZCB', 'quantity' => 171],
                    ['sku' => 'ZCC', 'quantity' => 65],
                    ['sku' => 'ZCD', 'quantity' => 129],
                    ['sku' => 'ZMF', 'quantity' => 17],
                    ['sku' => 'ZMD', 'quantity' => 24],
                    ['sku' => 'ZME', 'quantity' => 27],
                    ['sku' => 'ZMM', 'quantity' => 11],
                    ['sku' => 'ZMA', 'quantity' => 40],
                    ['sku' => 'ZMS', 'quantity' => 15],
                    ['sku' => 'ZMT', 'quantity' => 13],
                    ['sku' => 'ZMI', 'quantity' => 14],
                    ['sku' => 'ZTM', 'quantity' => 12],
                    ['sku' => 'ZTE', 'quantity' => 3],
                    ['sku' => 'ZTU', 'quantity' => 2],
                    ['sku' => 'ZMH', 'quantity' => 3],
                    ['sku' => 'ZXS', 'quantity' => 10],
                    ['sku' => 'ZXB', 'quantity' => 22],
                    ['sku' => 'ZXM', 'quantity' => 2],
                    ['sku' => 'ZXH', 'quantity' => 6],
                    ['sku' => 'ZX', 'quantity' => 1],
                    ['sku' => 'ZXA', 'quantity' => 13],
                    ['sku' => 'ZXU', 'quantity' => 1],
                    ['sku' => 'ZXE', 'quantity' => 2],
                    ['sku' => 'ZXO', 'quantity' => 1],
                    ['sku' => 'ZXK', 'quantity' => 1],
                    ['sku' => 'ZXT', 'quantity' => 8],
                    ['sku' => 'ZXW', 'quantity' => 5],
                    ['sku' => 'ZXC', 'quantity' => 1],
                    ['sku' => 'ZXTO', 'quantity' => 3],
                    ['sku' => 'ZHE', 'quantity' => 1],
                    ['sku' => 'ZHI', 'quantity' => 6],
                    ['sku' => 'ZHS', 'quantity' => 2],
                    ['sku' => 'ZNBA', 'quantity' => 44],
                    ['sku' => 'ZNB', 'quantity' => 1],
                    ['sku' => 'ZNM', 'quantity' => 1],
                    ['sku' => 'ZNH', 'quantity' => 2],
                    ['sku' => 'ZNU', 'quantity' => 5],
                    ['sku' => 'ZNA', 'quantity' => 2],
                    ['sku' => 'ZNO', 'quantity' => 1],
                    ['sku' => 'ZNG', 'quantity' => 1],
                    ['sku' => 'ZNI', 'quantity' => 2],
                    ['sku' => 'ZNR', 'quantity' => 1],
                    ['sku' => 'ZNTC', 'quantity' => 1],
                    ['sku' => 'ZNTO', 'quantity' => 1],
                    ['sku' => 'ZNHI', 'quantity' => 2],
                    ['sku' => 'ZNHB', 'quantity' => 3],
                    ['sku' => 'ZGU', 'quantity' => 14],
                    ['sku' => 'ZGW', 'quantity' => 1],
                    ['sku' => 'ZGE', 'quantity' => 3],
                ]
            ],
        ];

        $globalSetting = GlobalSetting::latestFirst();
        $inventoryDefaultMeasurement = $globalSetting->inventoryDefaultMeasurement;

        foreach ($orders as $order) {
            $manualCreatedAt = Carbon::parse($order['date']);
            $shippingDate = $manualCreatedAt;

            $salesOrder = SalesOrder::create([
                'number' => Sequence::generateSalesOrderSequence(),
                'customer_id' => 1,
                'quotation_date' => $manualCreatedAt,
                'shipping_date' => $shippingDate,
                'salesperson_id' => 1,
                'shipping_policy' => Transfer::AS_SOON_AS_POSSIBLE,
                'vehicle_type' => SalesOrder::MOTORCYCLE,
                'status' => SalesOrder::DRAFT,
                'shipping_method' => Transfer::DELIVERY,
                'source_id' => 2,
                'created_at' => $manualCreatedAt,
                'updated_at' => $manualCreatedAt,
            ]);

            $subtotal = 0;

            foreach ($order['items'] as $item) {
                $product = Product::where('internal_reference', trim($item['sku']))->first();
                if (!$product) {
                    continue;
                }
                $quantity = $item['quantity'];
                $salesOrderLineSubtotal = $product->sales_price * $quantity;
                SalesOrderLine::create([
                    'product_id' => $product->id,
                    'quantity' => $quantity,
                    'measurement_id' => $inventoryDefaultMeasurement->id,
                    'unit_price' => $product->sales_price,
                    'subtotal' => $salesOrderLineSubtotal,
                    'sales_order_id' => $salesOrder->id,
                    'created_at' => $salesOrder->created_at,
                    'updated_at' => $salesOrder->updated_at,
                ]);
                $subtotal += $salesOrderLineSubtotal;
            }
            $salesOrder->subtotal = $subtotal;
            $salesOrder->save();
            info("New manual sales order created {$salesOrder->number}");
        }
    }
}
